### ISSUE TITLE
Is there any documentation or tutorials available?

### ISSUE THREAD

**Issue by Karatesaurus-Rex** [Maxi35/pyrelay#1]
I am mildly proficient with python, but am struggling to pick up your syntax just from the single plugin bundled with the project.

The whole thing works phenomenally so far, and I would really like to get into some interesting developments soon.  Is there anyway you can post more plugins so I can learn by example if you do not have the time to create some tutorials for people to begin using the program?

Thank you very much for your time working on this project.  it's incredible and I simply cannot wait to get started with it.

**Comment by Maxi35** [comment]
Thanks for your kind words, I'll try to make some plugins showing how to use it, if there are any specific elements you want examples off just list them here and I'll try to make a tutorial plugin

**Comment by Maxi35** [comment]
Made two small plugins which should show how to reply to text and nexus, another one which shows how to move and enter the vault portal. Hope it is enough to get an idea of how to use it
