### ISSUE TITLE
struct.error: unpack requires a buffer of 2 bytes

### ISSUE THREAD

**Issue by MauritsArissen** [Maxi35/pyrelay#10]
Hey there I was working with the INVSWAP 
```py
testPacket = CreatePacket("INVSWAP")
testPacket.slotObject1.slotId = 2
testPacket.slotObject2.slotId = 11
client.send(testPacket)
```
However this gives me the error `struct.error: unpack requires a buffer of 2 bytes` where this should be working right?

**Comment by Maxi35** [comment]
Could you send more of the error? Because sending packet shouldn't be able to generate unpack errors.

**Comment by MauritsArissen** [comment]
Trace

Traceback (most recent call last):
  File "C:\Users\Arissen\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Arissen\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "D:\pyrelay-master\Networking\SocketManager.py", line 121, in _listen
    packet.read(self.reader)
  File "D:\pyrelay-master\Networking\Packets\Incoming\FailurePacket.py", line 12, in read
    self.errorPlace = reader.readStr()
  File "D:\pyrelay-master\Networking\Reader.py", line 50, in readStr
    strLen = self.readShort()
  File "D:\pyrelay-master\Networking\Reader.py", line 35, in readShort
    value = struct.unpack("!h", self.buffer[self.index:self.index+2])[0]
struct.error: unpack requires a buffer of 2 bytes

**Comment by Maxi35** [comment]
Ahh I see, the failure packet is causing the error (ironic), I'll have a look at it.
But the reason you are getting the failure packet sent is because you are not initializing all the variables in the invswap packet correctly. You can look in Data\SlotObjectData.py to see it's variables

**Comment by MauritsArissen** [comment]
Oh I see, well I can't get to figure the objectType of an item. Also what to put in for an empty inv slot?

**Comment by Maxi35** [comment]
objectType is just the item's id, so client.playerData.inv[slotId] will get you that. For an empty inv slot the objectType is simply -1

**Comment by MauritsArissen** [comment]
Oh but objectId then also the itemId right? Or am I getting that wrong

**Comment by Maxi35** [comment]
ObjectId is the objectId of which the slot belong to, so if the slot is in your inventory then the objectId is client.objectId, if the slot is in your vault then the objectId is the vault chest's objectId

**Comment by MauritsArissen** [comment]
I see I understand, thank you for the explaination
