### ISSUE TITLE
enter packet

### ISSUE THREAD

**Issue by leopaoca** [Maxi35/pyrelay#27]
How do hook enter packet? It dosn't seem to be working

**Comment by Maxi35** [comment]
Not sure what you mean by enter packet, as a packet with that name doesn't exist?

**Comment by leopaoca** [comment]
Like when a player joins nexus. I remember in nrelay there was that packet

**Comment by Maxi35** [comment]
Ahh yea but it was some special made functions he made, you can find players and players joining in the update packet. Then update their info with the newTick packet

**Comment by leopaoca** [comment]
ohhhhh! thanks for explaining! :)
