### ISSUE TITLE
Find position of another player

### ISSUE THREAD

**Issue by Karatesaurus-Rex** [Maxi35/pyrelay#31]
How can I enumerate the positions of all players in nexus, or a realm?  

I would like to find this information and print it to the console as part of a plugin.

The goal is to ultimately make a bot that walks to a player in nexus, and trades with them only once they are located on top of the player.

**Comment by Maxi35** [comment]
In the update packet you can loop over newObjs anc check if the objectType is a player class, these ids are located in constants/classIds.py. Then once you got the player(s) you need you can update info about them by comparing the tracked player's objectId with the objectIds in newTick.statuses.
Hope this helps

**Comment by Karatesaurus-Rex** [comment]
Apologies in advance, I still have a lot to learn.  Appreciate your time to help tremendously.

```
    @hook("update")
    def onUpdate(self, client, packet):
        for e in packet.newObjs:
            if e.objectType == 800:
                print("assassin")
```


if I am playing an assassin class, and I am in the same nexus or map as the bot, it will print assassin as expected.  How do I access the variables for the object?  For instance, if I want to print the name of the bot, I can just use print(client.playerData.name).

When I tried to do e.PlayerData.name, it does not work, I assume the object is not recognized as a playerData type class?

I am clearly doing something wrong here if you can point me in the right direction.  I'd like to start by being able to read the name of every player in nexus and output to console, and then I can work on figuring out how newTick.status works to triangulate position.

**Comment by Maxi35** [comment]
e is an objectData, from data/objectData.py, so to get the name you'll have to access the stats of the object. The stats are in e.status.stats, then you can loop over these and use constants/statTypes.py to find the name stat.
Posision of objects are also on the stat object so you can just find it by e.status.pos

**Comment by Karatesaurus-Rex** [comment]
```
 @hook("update")
    def onUpdate(self, client, packet):
        for e in packet.newObjs:
            if e.objectType == 800:
                charClassAndName = []
                charClassAndName.append("Assassin")
                for i in e.status.stats:
                    statType = str(i).split()[1]
                    if statType == "31":
                        charClassAndName.append((str(i).split()[3]))
                        print(charClassAndName)
                    else:
                        next
```


This is my naïve implementation for the assassin class only so far, is this what you mean?  Seems to work good enough, thank you for taking the time to help!

**Comment by Maxi35** [comment]
Would probably change it to something like this:
```python
    @hook("update")
    def onUpdate(self, client, packet):
        for e in packet.newObjs:
            if e.objectType == 800:
                charClassAndName = []
                charClassAndName.append("Assassin")
                for stat in e.status.stats:
                    if stat.statType == 31:
                        charClassAndName.append(stat.strStatValue)
                        print(charClassAndName)
```
Since you don't need to convert the class to a str, you can just directly access the variables

**Comment by Karatesaurus-Rex** [comment]
This is perfect for my needs, thank you very much!

**Comment by Karatesaurus-Rex** [comment]
My apologies Maxi,

Can you provide rough pseudo code on hooking the newTick packet so I can update the player position?

I got it working to move to the player, but this only works once for the initial time the player enters the nexus I cannot seem to update the target user position if target moves.


```
    @hook("update")
    def onUpdate(self, client, packet):
        global followTarget
        global followTargetLoc
        for e in packet.newObjs:
            if e.objectType == 800:
                charClassAndName = []
                charClassAndName.append("Assassin")
                for i in e.status.stats:
                    statType = str(i).split()[1]
                    if statType == "31":
                        charClassAndName.append((str(i).split()[3]))
                        print(charClassAndName)
                        print(e.status.pos)
                        print(followTarget)
                        if charClassAndName[1] == followTarget:
                            x = True
                            while x == True:
                                followTargetLoc = e.status.pos
                                client.nextPos = [followTargetLoc]
                                print(e.status.pos)
                                print(type(print(e.status.pos)))
                    else:
                        next
```

**Comment by Maxi35** [comment]
Yea sure I think this should work:
Add this in __init__
```
def __init__(...):
    self.targetName = "blabla"
```
For update
```python
    @hook("update")
    def onUpdate(self, client, packet):
        for e in packet.newObjs:
            if e.objectType == 800:
                for stat in e.status.stats:
                    if stat.statType == 31 and stat.strStatValue == self.targetName:
                        self.targetObjectId = stat.objectId
                        self.targetPos = stat.pos
                        print(charClassAndName)
```

```python
@hook("newTick")
def onNewTick(self, client, packet):
    for status in packet.statuses:
        if status.objectId == self.targetObjectId:
            self.targetPos = status.pos
```

**Comment by Karatesaurus-Rex** [comment]
Thank you again for taking all the time to help.

I seem to be having an issue with this line:
`self.targetObjectId = stat.objectId`

I get the error StatData object has no attribute object ID

**Comment by Karatesaurus-Rex** [comment]
```
    @hook("update")
    def onUpdate(self, client, packet):
        global followTarget
        global followTargetLoc
        global followTargetObjectID
        for e in packet.newObjs:
            if e.objectType == 800:
                #print(type(e))
                #print(e)
                charClassAndName = []
                charClassAndName.append("Assassin")
                for i in e.status.stats:
                    statType = str(i).split()[1]
                    if statType == "31":
                        charClassAndName.append((str(i).split()[3]))
                        print(charClassAndName)
                        print(e.status.pos)
                        print(followTarget)
                        if charClassAndName[1] == followTarget:
                            followTargetObjectID = e.status.objectId
                            followTargetLoc = e.status.pos
                            client.nextPos = [followTargetLoc]
                            print(e.status.pos)
                    else:
                        next

           # elif e.objectType == 782:
               # print ("wizard")
    @hook("newTick")
    def onNewTick(self, client, packet):
        global followTargetObjectID
        for status in packet.statuses:
            if status.objectId == followTargetObjectID:
                #print(status)
                client.nextPos = status.pos
                time.sleep(.5)
```

I think it's almost done.  I couldn't get your class based code to work so I'm using sloppy global vars.

getting an issue with the client.nextPos portion, for some reason there is a type error:
if len(self.nextPos) > 0:
TypeError: object of type 'WorldPosData' has no len()

any ideas?

**Comment by Maxi35** [comment]
Yes it is because client.nextPos is a list, so you should do: client.nextPos.append(status.pos)

**Comment by Maxi35** [comment]
I'll take it as this is solved, open again if you still have problems
