### ISSUE TITLE
Bad message reveived after game update

### ISSUE THREAD

**Issue by Wifelly** [Maxi35/pyrelay#34]
Yo, game have been updated. Bumping new version to versionFile dosnt seem to help
After initial hello packet you reveive: "Bad message reveived". Some changes in packets probably

**Comment by Maxi35** [comment]
Should have been fixed in [73a136c](https://github.com/Maxi35/pyrelay/commit/73a136c43f9144b75a6acd350f9210bebdbd6988), have you downloaded the latest version?

**Comment by Wifelly** [comment]
sry, havent seen this commit in time. any tips on packet change investigation btw?

**Comment by Maxi35** [comment]
Haha no problem, I just use a proxy and see what packets it sends nothing fancy
