### ISSUE TITLE
reply back plugin

### ISSUE THREAD

**Issue by Lynx-The-Dev** [Maxi35/pyrelay#35]
import time

from Networking.PacketHelper import CreatePacket
from PluginManager import hook, plugin

#All plugins should have a plugin decorater
@plugin(active=True)
class ReplyPlugin:
    def __init__(self):
        self.toReply = ""

    #To hook a packet use the hook decorator with the packet type you wish to hook
    @hook("text")
    def onText(self, client, packet): 
        replyPacket = CreatePacket("PLAYERTEXT")
        replyPacket.text = f"/tell [toreply] Hey! how are u"
        client.send(replyPacket)
  
        
I'm struggling trying to make the bot reply to anyone.  I've been tiddling with this for hours and I've been stuck.  It sends the packet, but I never receive anything.  If I let it run, it eventually spams packets and I get a temp Ip ban.  Any help is greatly appreciated as I'd like to make something special for my guildmates.

**Comment by Lynx-The-Dev** [comment]
first comment sorry if its improper

**Comment by Maxi35** [comment]
I recommend reading how it is done in the reply-plugin https://github.com/Maxi35/pyrelay/blob/master/Plugins/ReplyPlugin.py, but some of the things you are doing wrong is: having [] around toreply. Seding a reply everythime you get a textPacket, make sure the textPacket is sent to you in a whisper. Also toreply is not defined, did you mean self.toReply?

**Comment by Lynx-The-Dev** [comment]
alright I understand now, thank you.
