### ISSUE TITLE
Other Player Tracking

### ISSUE THREAD

**Issue by Devolutional** [Maxi35/pyrelay#36]
I understand the project has little documentation on functionality, however can i get some insight on how to actively get player position data per tick?

**Comment by Maxi35** [comment]
Hey sure, you can start by reading an [older issue](https://github.com/Maxi35/pyrelay/issues/31), if you have more questions I'll be happy to answer

**Comment by Devolutional** [comment]
I have taken reference from this older post, however maybe the structure has changed?

```
    @hook("update")
    def onGlobalUpdate(self, client, packet):
        stat_types = StatTypes.StatTypes()

        for object in packet.newObjs:
            class_lookup = ClassIds.ClassIdLookup.get(object.objectType)
            if(class_lookup):
                for stat in object.status.stats:
                    if(stat.statType == stat_types.NAMESTAT):
                        if(stat.strStatValue == "Atomicjell"):
                            self.targetObjectId = stat.objectId
                            self.targetPos = stat.pos

    @hook("newTick")
    def captureTargetObject(self, client, packet):
        for status in packet.statuses:
            if(status.objectId == self.targetObjectId):
                self.targetPos = status.pos
```

self.targetObjectid = stat.objectId fails saying StatData has no attribute objectId.

ClassIdLookup is something I made inside of ClassIds reversing the list to id:name

**Comment by Devolutional** [comment]
Essentially I just want something to have the bot account follow the target players position.

**Comment by Devolutional** [comment]
```
    @hook("newTick")
    def followTrack(self, client, packet):
        time = client.getTime()

        new_worldpos = WorldPosData.WorldPosData(target_client.pos.x, target_client.pos.y - client.getSpeed(time))
        client.nextPos.append(new_worldpos)
```

this is my current function to move the bot to a desired path, but need to get target_client first

**Comment by Maxi35** [comment]
This line `self.targetObjectId = stat.objectId` should be `self.targetObjectId = object.status.objectId`

Not sure what you are trying to do here: `new_worldpos = WorldPosData.WorldPosData(target_client.pos.x, target_client.pos.y - client.getSpeed(time))`, but when you insert a pos into client.nextPos, it will automatically move smoothly to that position

**Comment by Devolutional** [comment]
I was testing some things out haha

Yes I have it working now. Is there a way to have the bot use abilities and shoot at the moment?

**Comment by Devolutional** [comment]
Would you have any IM platforms such as discord?

**Comment by Maxi35** [comment]
Yea sure you can add me on discord: ``
