### ISSUE TITLE
Error: 15

### ISSUE THREAD

**Issue by Zaclin-GIT** [Maxi35/pyrelay#38]
Just added an account, tried to run Pyrelay and am getting this error. Doesn't look like the game has updated since the latest release, so I don't believe its packet related. Tested it on a different machine and still getting the same error. No clue what is going on. 

Connecting to 54.234.226.24
Error: 15
Client forcefully disconnected from 54.234.226.24

Where do these error codes come from? is it a packet id?

**Comment by Extacy** [comment]
https://github.com/Maxi35/pyrelay/blob/64837cb3c2f626bda71309403fba25e3c64835a7/Client/Client.py#L359-L370

Looks like you received a FailurePacket with and errorId of 15, which is that the server is full and you were placed in the queue.
From a quick search of this repo I don't think pyrelay handles server queuing, but what should happens is:

1. Receive FailurePacket (don't reconnect)
2. Wait for QueueMessagePacket
3. Wait x seconds and attempt to reconnect
4. Repeat

But for now you could just try connecting to a different server

**Comment by Zaclin-GIT** [comment]
Can always count on Extacy to have the method ;)

Appreciate your help.
