### ISSUE TITLE
struct.error: unpack requires a buffer of 1 bytes

### ISSUE THREAD

**Issue by hannutho** [Maxi35/pyrelay#4]
Since the new update there is a problem in some buffer sizes in the reader. Have you had a look into this and found a way to resolve this? I haven't found any fix for this.

**Comment by Maxi35** [comment]
Yea in newest update some packets got changed, don't know when I'll have it fixed

**Comment by Maxi35** [comment]
Fixed in [50f5b45](https://github.com/Maxi35/pyrelay/commit/7096b0a0ebb1305d8970645efc3656e8f7f51947)
