### ISSUE TITLE
Version 4.2.0.0 - Error 4

### ISSUE THREAD

**Issue by trevinangel** [Maxi35/pyrelay#40]
First of all I would like to say I throughly appreciate your work. It is truly something us Realm enjoyers and coders alike can enjoy. On to the problem I am encountering; I am getting the error 4 message "s.update_client". After reading other threads here I see that this is due to a recent game update which occurred on 3/12. I have changed the game version manually within gameVersion.txt as recommended in another thread and that did not work. Now I am sure I could figure out how to fix this but instead of spending hours trying to do so I thought I would come here and ask for help first. Any assistance is greatly appreciated. Thanks!

**Comment by Maxi35** [comment]
Hey thanks for the heads up, as far as I can see it didn't work because the newest version is actually `4.2.0.1.0`, make sure you write the full game version when it asks you to update it

**Comment by trevinangel** [comment]
Oh that was it. Thanks!
