### ISSUE TITLE
Incoming Party Invite Throws Error

### ISSUE THREAD

**Issue by Zaclin-GIT** [Maxi35/pyrelay#45]
When inviting a client to a party it throws this error - ValueError: Invalid Packet type: CHATLOGOUTMSG.

**Comment by Maxi35** [comment]
Ahh looks like they reused a very old packet id, will take a look at it later, but a quick fix is just to remove `208: "CHATLOGOUTMSG"` from `Constants/PacketIds.py`

**Comment by Zaclin-GIT** [comment]
Appreciate the follow up on this. I'm pretty new to python/rotmg networking, but I was able to learn how to add the packets as well as the required data to make this work. Ill attach them here incase it saves you some time. 
[Updated.zip](https://github.com/user-attachments/files/17563818/Updated.zip)
