### ISSUE TITLE
Rotmg patch

### ISSUE THREAD

**Issue by FengchiW** [Maxi35/pyrelay#5]
Primary Issue:

Error: 4 at Game
server.update_client
No clients are active - exiting

Probably due to the update, unsure if it is my side.

Other issues:

- The crypto library overwrites the crypto directory with RC4 and RSA.
A simple solution to this is making sure the local package included < add __init__.py to the crypto dir>

**Comment by Maxi35** [comment]
Yea there was an update to rotmg earlier today, to fix it just open "Client/client.py" and edit the line "self.buildVersion" to "1.3.0.2.0". The crypto issues will be addressed in the next push 👍

**Comment by FengchiW** [comment]
Can I get a contact @Maxi35

**Comment by Maxi35** [comment]
What do you mean?

**Comment by FengchiW** [comment]
discord, email? I want to learn more about py relay.

**Comment by Maxi35** [comment]
Ahh okay, you can contact me on discord
